server:
  port: 9903

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:9900/eureka/

spring:
  application:
    name: gateway-service
  cloud:
    loadbalancer:
      retry:
        enabled: false
    gateway:
      routes:
        - id: login-service
          uri: http://localhost:9901
          predicates:
            - Path=/lservice/**

        - id: register-service
          uri: http://localhost:9902
          predicates:
            - Path=/rservice/**