server:
  port: 9904

#eureka:
#  instance:
#    preferIpAddress: true
#    instance-id: ${spring.cloud.client.ip-address}:${server.port}
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:9900/eureka/

spring:
  application:
    name: dorm-service
#  cloud:
#    loadbalancer:
#      retry:
#        enabled: false
  datasource:
    url: jdbc:mysql://mysql:3306/itstudy?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  type-aliases-package: com.example.login.entity
  mapper-locations: classpath:mapper/*.xml
