server:
  port: 9901

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:9900/eureka/

spring:
  application:
    name: login-service
  cloud:
    loadbalancer:
      retry:
        enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/itstudy?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: lc1997622
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.example.login.entity
  mapper-locations: classpath:mapper/*.xml
